name: tooling
clusterService: true
namespace: tooling
description: Tooling services Argo WF, Harbor.

project:
  name: tooling
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: argowf
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-argo-wf.git"
      targetRevision: dependency
      path: argo-wf
      valuesFile: "argowf.yaml"
  - name: argo-events
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-argo-events.git"
      targetRevision: dependency
      path: argo-events
      valuesFile: "argo-events.yaml"
  - name: harbor
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-harbor.git"
      targetRevision: dependency
      path: harbor
      valuesFile: "harbor.yaml"
  - name: vault
    source:
      repoURL: "https://github.com/Open-Olympus-Project/tooling-vault.git"
      targetRevision: dependency
      path: vault
      valuesFile: "vault.yaml"
