name: rook-ceph
clusterService: true
namespace: rook-ceph
description: Rook.

project:
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: rook
    source:
      repoURL: "https://github.com/distributed-technologies/services-rook.git"
      targetRevision: rook-dependency
      path: chart
      valuesFile: "rook.yaml"
  - name: ceph
    source:
      repoURL: "https://github.com/distributed-technologies/services-ceph.git"
      targetRevision: fileTest
      path: chart
      valuesFile: "ceph.yaml"
