{{- $root := . -}}
{{- range $path, $_ := .Files.Glob "**/**/config.yaml" }}
    {{ $project := $root.Files.Get $path | fromYaml }}
    {{- range $project.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  # You'll usually want to add your resources to the argocd namespace.
  namespace: {{ $root.Release.Namespace }}
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: {{ $project.project.name }}

  # Source of the application manifests
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    path: {{ .source.path }}
    helm:
      version: v3
      values: |
        {{- $valuesFilePath := printf "%s/%s" ($path | dir) .source.valuesFile }}
        {{- $valuesFile := $root.Files.Get $valuesFilePath }}
{{ tpl $valuesFile $root | indent 8 }}
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $project.namespace }}

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

    {{- end }}
{{- end }}
