# serviceDomain: {{ .Values.fqdn }}

image:
  name: traefik
  tag: "v2.4.6"
  pullPolicy: IfNotPresent

# These will override the name that is used for all resources.
# The name defaults to .Chart.Name and the fullname defaults to .Release.Name
nameOverride: ""
fullnameOverride: ""

# Configure ports. A service is only created if the port config has a serviceType
ports:
  traefik:
    port: 8080
    protocol: TCP
  web:
    serviceType: NodePort
    port: 80
    nodePort: 32286
    protocol: TCP

serviceAccount:
  name: ""
